FROM appsmith/appsmith-ce

ARG ENCRYPTION_PASSWORD
ARG ENCRYPTION_SALT
ARG MONGODB_URI

# Environment variables for Appsmith
ENV APPSMITH_ENCRYPTION_PASSWORD=$ENCRYPTION_PASSWORD
ENV APPSMITH_ENCRYPTION_SALT=$ENCRYPTION_SALT
ENV APPSMITH_MONGODB_URI=$MONGODB_URI

CMD ["./start-Appsmith.sh"]