FROM appsmith/appsmith-ce

ARG ENCRYPTION_PASSWORD
ARG ENCRYPTION_SALT
ARG MONGOHOST
ARG MONGOPORT
ARG MONGOUSER
ARG MONGOPASSWORD
ARG MONGO_URL

# Environment variables for Appsmith
ENV APPSMITH_ENCRYPTION_PASSWORD=$ENCRYPTION_PASSWORD
ENV APPSMITH_ENCRYPTION_SALT=$ENCRYPTION_SALT
ENV APPSMITH_MONGODB_URI=$MONGO_URL

CMD ["./start-Appsmith.sh"]
